name: Create a Release?

on: 
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '1 1 1 1 1'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Create a Release
        uses: actions/create-release@v1
        with:
          # The name of the tag. This should come from the webhook payload, `github.GITHUB_REF` when a user pushes a new tag
          tag_name: github.GITHUB_REF
          # The name of the release. For example, `Release v1.0.1`
          release_name: Release github.GITHUB_REF
          # `true` to create a draft (unpublished) release, `false` to create a published one. Default: `false`
          draft: true
          # `true` to identify the release as a prerelease. `false` to identify the release as a full release. Default: `false`
          prerelease: true
